### PR TITLE
fix: update dropzone deps

### PR DESCRIPTION
**Pull request by isaackps**
## In this PR:

- fix an error where the error message is displaying for a short while before verifying the document in windows.

### CODE REVIEW

**Comment by simboonlong** [comment]
refer to this fix instead to see if it works -> https://github.com/TradeTrust/tradetrust-website/pull/593

**Comment by isaackps** [comment]
> refer to this fix instead to see if it works -> #593

nope, it didn't fix the issue with the double loading on windows

**Comment by simboonlong** [comment]
check with someone else who has windows env in the team to review this pr?

**Comment by isaackps** [comment]
> check with someone else who has windows env in the team to review this pr?

ok sure. 

But just an update the certificate img is the issue, it is being dragged into the dropzone, so i have made the img tag undraggable.

**Review by simboonlong — APPROVED** [review]

**Pull request merged**
