### PR TITLE
feat: Tailwind CSS Migration from @emotion/styled

### PR DESCRIPTION
**Pull request by osslgtm**
## Summary
Migration from @emotion/styled to Tailwind CSS

## Changes
Removed the use of styled, switched styling to Tailwind and to fit in to the design patterns in @tradetrust-ui-components

## Issues
https://www.pivotaltracker.com/story/show/181055490

### CODE REVIEW

**Review by simboonlong — APPROVED** [review]
lgtm

**Comment by superical** [comment]
@puayhiang Can we mark this PR as ready when it's done? Thanks!🙏

**Comment by osslgtm** [comment]
@superical Ok to merge ?

**Comment by superical** [comment]
@puayhiang Thanks! I just tried to run the PR and the network selection component looks a little different from its original styling. Just to check, is this due to the limitation of Tailwind? Or is there something else that can be done to match their styles?

In this PR:
image

Original:
image

**Comment by GPHofficial** [comment]
It's made to look like the menu bar on the left, maybe i can check with Jeffery on this ?

**Comment by osslgtm** [comment]
It's made to look like the menu bar on the left, maybe i can check with Jerry on this ?

**Comment by superical** [comment]
Ahh… It’s intentional. I see. I initially thought it was due to some limitations. Okay sure, you can check to see if the design of the component is alright first. If so, then we can proceed with merging. Thanks!😊

PS: The next step after this is to move that network selector component down on the verify page based on the new design. So it will be easier in the next step once we get the design right.

**Comment by superical** [comment]
Sorry!! I accidentally merged into #506 after resolving a merge conflict forgetting that I was previously testing this PR.🤦‍♂️
I have reverted the merge. Will need to re-create another PR for this change.

**Pull request merged**
