### PR TITLE
feat(hedera): added support for hedera network

### PR DESCRIPTION
**Pull request by piruthivi3232**
added mainnet and testnet hedera network configurations.

## Summary

feat(hedera): added support for hedera network by krypc

## Changes

- added mainnet and testnet hedera network configurations.

### CODE REVIEW

**Comment by superical** [comment]
Please update branch and fix errors.

**Comment by piruthivi3232** [comment]
errors fixed.

**Comment by superical** [comment]
Pls post some screenshots of the frontend to show that you have tested it and that it's working on KrypC's desired blockchain. Thanks.

**Comment by learntbt** [comment]
screen1
screen2
screen3
screen4
screen5

screenshot added for your reference

**Comment by piruthivi3232** [comment]
screen1
screen2
screen3
screen4
screen5

screenshot added for your reference

**Comment by isaackps** [comment]
Thank you for the screenshots, 
next step is to include the tests:
- Display - Owner, Holder, Surrender Status, Endorsement Chain
- Status Checks - Issuance Check -> Validity check on smart contract(Document Store & Token Registry), Issuer Check -> DNS Records, Tamper Check -> hash corresponds to Document
- transfers - Transfer Owners, Transfer holder
- owner Change Request - Nominate owner, Endorse owner
- Surrender - Surrender, Accept Surrender, Reject Surrender
- User Flow with Roles - Transfer Owners -> both owner and holder in a single transaction, nominate (by owner) then endorse nomination (by holder), surrender (by owner and holder) then accept surrender (by ACCEPTOR_ROLE), surrender (by owner and holder) then reject surrender (by RESTORER_ROLE)

**Comment by piruthivi3232** [comment]
We just need to add the test cases, correct?

**Comment by isaackps** [comment]
Yes, the changes looks good, just need to update the test cases for this repo.

**Comment by isaackps** [comment]
Hi,
can you add in a demo TT document too, thanks

**Pull request closed without merging**
