### PR TITLE
chore: update rinkeby default rpc

### PR DESCRIPTION
**Pull request by superical**
## Summary

As Infura is ending their support for Rinkeby in a week's time, we will have to move away from them if we want to keep Rinkeby for the time being. This PR updates the Rinkeby RPC to use a different one.

Note: We should also consider an auspicious date to deprecate Rinkeby on TradeTrust whenever ready.

## Changes

- Update Rinkeby RPC

## Issues

- https://www.pivotaltracker.com/story/show/183423831

### CODE REVIEW

**Comment by superical** [comment]
As for Ropsten, the dev site is going to stop working with it after Infura drops their support on 5 Oct.🥲

**Comment by isaackps** [comment]
> As for Ropsten, the dev site is going to stop working with it after Infura drops their support on 5 Oct.🥲

in that case, should we just drop support for Rinkeby too?

**Comment by isaackps** [comment]
i just checked, allthatnode.com also deprecated rinkeby testnet endpoint.

**Comment by superical** [comment]
> > As for Ropsten, the dev site is going to stop working with it after Infura drops their support on 5 Oct.🥲
> 
> in that case, should we just drop support for Rinkeby too?

Yea, you are right. We should also consider an auspicious date to deprecate Rinkeby on TradeTrust whenever ready. This PR is only relevant if we haven't yet decided when we want to deprecate Rinkeby or if there are still users testing against Rinkeby on our site and we want to extend the support a little bit more. Maybe this is something we can discuss tomorrow morning with the product team if they are good with us taking it down.

**Comment by superical** [comment]
> i just checked, allthatnode.com also deprecated rinkeby testnet endpoint.

Woo! Didn't see this coming so soon! haha! Thanks for checking it again, @isaackps! 🙇‍♂️
I've changed it again: https://github.com/TradeTrust/tradetrust-website/pull/627/commits/f4ca26853843a1490528f6f0bd8fc19e72ca81de

Don't think we can expect to rely on this for long too.😐

**Review by isaackps — APPROVED** [review]
LGTM!

**Pull request merged**
